# Generated by Django 5.2 on 2025-04-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="General", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(default="Unisex", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="products/product1.jpg", upload_to="products/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
