# Generated by Django 5.2 on 2025-04-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0003_remove_product_created_at_remove_product_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("non_delivered", "Non-delivered"),
                    ("delivered_not_confirmed", "Delivered but not confirmed"),
                    ("delivered_confirmed", "Delivered and confirmed"),
                ],
                default="non_delivered",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("not_paid", "Not Paid"), ("paid", "Paid")],
                default="not_paid",
                max_length=20,
            ),
        ),
    ]
