# Generated by Django 5.2 on 2025-04-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_order_status_alter_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
