# Generated by Django 5.2 on 2025-04-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_order_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transaction_hash",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
