# Generated by Django 5.2 on 2025-04-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_rename_created_at_order_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("rings", "Rings"),
                    ("necklaces", "Necklaces"),
                    ("bracelets", "Bracelets"),
                    ("earrings", "Earrings"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("unisex", "Unisex")],
                default="unisex",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="products/product1.jpg", upload_to="products/"
            ),
            preserve_default=False,
        ),
    ]
