# Generated by Django 5.2 on 2025-04-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_order_delivery_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
