# Generated by Django 5.2 on 2025-05-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_order_payment_method_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
