# Generated by Django 5.2 on 2025-05-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_order_stripe_payment_intent_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="gender",
        ),
        migrations.AddField(
            model_name="product",
            name="main_category",
            field=models.CharField(
                choices=[
                    ("clothing", "Clothing"),
                    ("shoes", "Shoes"),
                    ("bags", "Bags"),
                    ("accessories", "Accessories"),
                    ("self-care", "Self-care"),
                    ("school", "School"),
                    ("newborn", "Newborn"),
                    ("toys", "Toys"),
                ],
                default="something",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("men", "Men"),
                    ("women", "Women"),
                    ("girls", "Girls"),
                    ("boys", "Boys"),
                    ("babies", "Babies"),
                ],
                default="everybody",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=100),
        ),
    ]
