# Generated by Django 5.2 on 2025-05-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_remove_product_gender_product_main_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("not_delivered", "Not Delivered"),
                    ("in_progress", "In Progress"),
                    ("delivered_not_confirm", "Delivered Not Confirmed"),
                    ("delivered_confirm", "Delivered Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="not_delivered",
                max_length=50,
            ),
        ),
    ]
