# Generated by Django 4.2.1 on 2025-06-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_remove_order_product_remove_order_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("not_delivered", "Not Delivered"),
                    ("in_progress", "In Progress"),
                    ("delivered_not_confirm", "Delivered Not Confirmed"),
                    ("delivered_confirm", "Delivered Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("return_requested", "Return Requested"),
                    ("refunded", "Refunded"),
                ],
                default="not_delivered",
                max_length=50,
            ),
        ),
    ]
